### ISSUE TITLE
Page title is missing

### ISSUE THREAD

**Issue by tato** [lRaulMN7/raultelo.me#2]
I have notice that the title of your website (https://raultelo.me/) is not showing on my machine. I would expect to see a title on any website in order to know what the website is about. When I visit your website, I am lost! I don't know what you're talking about! Is this your personal website? Is this someone else's website? I have no idea. Please, fill the title of your website, so I can sleep in peace.

Regards

**Comment by lRaulMN7** [comment]
Fixed at #4
