### ISSUE TITLE
The language of your website is unclear

### ISSUE THREAD

**Issue by tato** [lRaulMN7/raultelo.me#3]
Help!! I don't know what language the website is written on!!! Fast, add the `lang="..."` attribute on your `html` tag, before it's too late!!!!!

Feel free to critique this issue, for I have not thought it through.

Regards

**Comment by lRaulMN7** [comment]
I'll work on it this weekend! Thanks a lot for your research and your time.

**Comment by tato** [comment]
It has been a pleasure to work with you (so far!)

**Comment by lRaulMN7** [comment]
Fixed at #4
